### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by Alex-Beh** [aychaplin/ur5_pick_place#2]
TODO list:
- [x] fix potential bug
- [x] restructure the package. Can refer to these two packages ([ur_ws](https://github.com/borninfreedom/ur_ws) & [ur5](https://github.com/utecrobotics/ur5))
- [x] function to check whether the current goal is reachable or not
- [x] to review - How to import tutorial class from ur_pick_place pkg in ur_smach pkg
- [x] continue state machine (at least one cycle of pick and place)
- [x] make robot move! - How the different state get access to move group interface
- [ ] Change from [smach](http://wiki.ros.org/smach) to [smacc library](https://github.com/reelrbtx/SMACC)

**Comment by Alex-Beh** [comment]
Do this after finish the state machine code 
- [ ] rename the variable name (MoveGroupPythonIntefaceTutorial -> UR_ARM_MoveGroup or something else)
